# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]

  - repo: local
    hooks:
      - id: sphinx-build
        name: sphinx-build
        entry: sphinx-build
        args: ["-b", "html", "docs", "docs/_build/html", "-W", "--keep-going"]
        language: system
        pass_filenames: false
        files: ^docs/
        env:
          CI: "false"
