name: Build and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install docs dependencies
        run: |
          if [ -f docs/requirements.txt ]; then
            uv pip install --system -r docs/requirements.txt
          else
            uv pip install --system sphinx furo
          fi

      - name: Build Sphinx docs
        run: sphinx-build -b html docs docs/_build/html -W --keep-going

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
